### ISSUE TITLE
Multiple collections with one Numishare and different collection images

### ISSUE THREAD

**Issue by Msch0150** [ewg118/numishare#105]
I have setup Numishare using Docker. I created several collection.
The overal goal is to add different start-images like for 

http://numismatics.org/chrr/ and http://numismatics.org/crro/

So far I found out that I could add a line like:

`<img` src="http://numismatics.org/themes/ocre/images/banner.jpg" style="width:100%">

to the body section in "xslt/pages/index.xsl". But for that I need different "index.xsl" for each collection.
I setup the "themes" folder like described in https://github.com/ewg118/numishare/wiki/Numishare-Themes but it looks like that the system always uses the ui folder (hard coded?) instead of the folder in themes directory.

Then I saw the info in https://github.com/ewg118/numishare/wiki/Numishare-Themes#altering-numishare-public-ui-pages-on-a-per-project-basis. But unfortunately the system response with:

Orbeon Forms - An Error has Occurred

An error has occurred in Orbeon Forms. You may want to try one of the following:

    If this error occurred when you followed a link, press your browser's Back button.
    If the above does not work, try reloading the page:
        With Firefox: hold down the shift key and click the Reload button in your browser toolbar.
        With Safari and Chrome: click the Reload button in your browser toolbar.
        With Internet Explorer: hold down the control key and click the Reload button in your browser toolbar. 
    Return home.

The line looks like:
        
        <page path="/numishare/mymint/" model="xpl/models/config.xpl" view="file:///usr/local/projects/numishare/xpl/views/pages/index.xpl"/>

Info: I just left the /usr/local/projects/numishare directory as it is, just to see something.
The site url looks like: http://localhost:8081/orbeon/numishare/mymint/

Am I doing something worng?

**Comment by ewg118** [comment]
I need to update the documentation for that section since Orbeon disabled the file:// protocol that can access content anywhere in the filesystem for security purposes. The oxf:// protocol must be used, which refers to `orbeon/WEB-INF/resources`. Therefore, symlinks must be placed in the Orbeon webapp to be able to access the XPL/XSLT for other projects.

 * Navigate to the resources folder and create `numishare-projects`
 * cd into `numishare-projects` and create a symlink to your `mymint` project which has its own index.xslt, e.g., /usr/local/projects/mymint
 * Take a look at the main page-flow.xml in Github as your guide, and you can change the path of the index.xsl to your own project with the following: `<page path="/numishare/mymint/" model="xpl/models/config.xpl" view="oxf:/numishare-projects/mymint/xpl/views/pages/index.xpl"/>`

**Comment by Msch0150** [comment]
That seems to solve the problem. Thanks.
I will make some further tests.

**Comment by Msch0150** [comment]
Works, thanks.
