### ISSUE TITLE
Configurable info pages (main menu)

### ISSUE THREAD

**Issue by Msch0150** [ewg118/numishare#108]
As an ehancement:

I would be nice to have a configurable (info) page in the main menu, example:

Browser|Search|Maps|Compare|APIs|<my_info_page>

If I enter some info in the admin UI for the <my_info_page> like "Menu Titel|<language>" and "Page Content|<language>" then it gets displayed in the public interface.
Background: Here could be entered some additional info and explainantions for abbreviations, methods etc.

**Comment by Msch0150** [comment]
So similar to the "About" menu in OCRE.

**Comment by ewg118** [comment]
This is possible, but adding info pages through the Numishare Settings page isn't well-supported anymore. I do an end-run by inserting the info pages directly into the config.xml for the project. That's typically because the WYSIWYG HTML editor doesn't necessarily have all of the controls I want, so I construct the HTML for the page myself and insert it into the config.

Find the `<pages>` element in config.xml in eXist-db.

Insert page like the following:

```
<page public="1" stub="about" id="about">
    <content lang="en">
        <title>About PELLA</title>
        <short-title>About</short-title>
        <text>
            <h2>About PELLA</h2>
            <p>PELLA is a project of the American Numismatic Society directed by Dr. Peter van Alfen. The web database, based on the Numishare platform, has
                been developed by Ethan Gruber.</p>
            <p>Substantial work in developing PELLA has been carried out by Prof. Andrew Meadows (Oxford University). Cynthia Cheng, Yoorim Choi, Sylvia
                Czander, Elena Ferrero, and Clara Sanchez provided considerable assistance in organizing material within the ANS collection. Alan Roche is
                responsible for the photographs of ANS coins. At the British Museum, Martin Price, former Curator of Greek coins, was instrumental in
                cataloguing this material. Amelia Dowler is the British Museum's current curator of this series. Prof. Bernhard Weisser and Dr. Karsten Dahmen
                have catalogued the material at the Münzkabinett of the Staatliche Museen zu Berlin.</p>
            <p>Current contributors to the project are the ANS, the Münzkabinett of the Staatliche Museen zu Berlin, and the British Museum.</p>
            <p>Translations have been provided by the following:</p>
            <ul>
                <li><strong>German:</strong>Karsten Dahmen</li>
                <li><strong>French:</strong>Frédérique Duyrat</li>
            </ul>
        </text>
    </content>
</page>
```

- stub: this forms part of your URL, eg mysite.org/about
- content: repeatable element for multiple languages
- title: the HTML title of the page in the `<head>`
- short-title: the name of the page as it will appear in the navigation bar in Numishare.
- text: insert all of your HTML for the page in here.

You can change the order in which your info page appears in the navigation menu by changing the order of `<tab id="pages" />` in the `<navigation>` element in the config file.

**Comment by Msch0150** [comment]
Works perfectly. Thanks!
