### ISSUE TITLE
"unwanted" namespace in NUDS/XML?

### ISSUE THREAD

**Issue by Msch0150** [ewg118/numishare#116]
I am not sure if this is a wanted or bad behaviour.:

http://numismatics.org/ocre/id/ric.10.zeno(2)_e.974.xml

The denomination looks like:
<**nuds:**denomination xlink:type="simple" xlink:href="http://nomisma.org/id/ae4">AE4</**nuds:**denomination>

while the same tag look for other items like (ex. http://numismatics.org/ocre/id/ric.9.tri.107B.xml):

<denomination xlink:type="simple" xlink:href="http://nomisma.org/id/ae4">AE4</denomination>

So without the namessapce "nuds:". 
There are many other examples for the usage of "nuds:" and it looks like that this is in use by the coins for RIC X only.

Background: 
If this is a regular nuds syntax, then I have have to take care about it in my processing.

**Comment by ewg118** [comment]
I'm not exactly sure how the prefixes got there. It must have been related to PHP script that generates the OCRE data, but since I've copied and pasted functions between various scripts for other type corpora, it appears some of this behavior has been replicated into Hellenistic Royal Coinages. This could also be a product of running files through an XSLT transformation at some point, or perhaps even some weird effect from creating eXist-db backups. 

I replaced all of the NUDS files in OCRE, so there are presently no extraneous prefixes there. These namespaces don't affect XSLT transformations, but they could affect processing in other languages, if operating on element name alone without referencing the namespace URI.

**Comment by ewg118** [comment]
Upon further examination, I still have the original XML files for Antigonid Coins Online that I uploaded into eXist-db on our older server. On the current server (we migrated a month ago), many or all XML files have a nuds: prefix on the denomination, whereas the sources files do not. I am going to try to test some things in eXist-db, but I think we can eliminate issues with any of my scripts for generating the NUDS.

**Comment by ewg118** [comment]
I'm closing this, since it's unresolveable on my end because eXist-db sometimes arbitrarily inserts the nuds prefix. Depending on what programming language you use, you should be able to resolve element names by namespaces rather than relying purely on the "XPath" name(), which variably could be `nuds:denomination` or `denomination`. This isn't a problem in Numishare itself because of the namespacing inherent in the XSLT.
