### ISSUE TITLE
Programmatic methods

### ISSUE THREAD

**Issue by Msch0150** [ewg118/numishare#141]
Is there a recommended way or best practice how to perform in a programmatic way to:

publish all approved objects
reindex all published objects
unpublish all objects

other than crawling through the response of the admin interface, search for the collection name, get the id, post the prepared xml structure?

**Comment by ewg118** [comment]
It is possible to execute a series of processes externally in a script by interacting directly with the eXist XML database and Solr.

For publish all approved objects:

1. First, you'll need to get a list of IDs for which you extract the Solr-compliant XML metadata that will be indexed. In the XQuery at https://github.com/ewg118/numishare/blob/master/xforms/admin.xhtml#L410 , but replace the string "COUNT" with an integer. 100 is a good number. This XQuery will separate blocks of IDs by the pipe, '|', character, with a comma character every 100 IDs. You'll have to split this large string by the appearance of the comma so that you'll have blocks of 100 IDs to index and iterate the following steps.
2. The next step is to GET the Solr XML document from Numishare through a URL, described by the XForms submission at https://github.com/ewg118/numishare/blob/master/xforms/admin.xhtml#L730. The URL is `http://localhost:8080/numishare/projectname/ingest?identifiers=id1|id2|id3`. Be sure to URL encode the `identifiers` parameter. This URL will deliver you a bulk Solr XML file for these IDs, in all of the languages you might have activated in Numishare.
3. Now you just want to POST this file into Solr to the URL, for example, `http://localhost:8983/solr/numishare/update`.
4. Then you want to POST the XML string `<commit/>` to the Solr URL above.

For reindexing published objects, the first step is replaced, where you query Solr for currently published objects rather than XQuery for all XML files within the collection. This feature isn't actually in Numishare anymore. It was removed some time ago. Essentially you need to submit a Lucene query to Solr for `collection-name:projectname` and you can filter the response so that only the recordId field is returned. You'll want to iterate batches of 100, such as the above example.

For unpublishing all objects, this is merely a POST of a Solr query that deletes the records from the project:

You would post
    <delete>
        <query>collection-name:projectname</query>
    </delete>

to `http://localhost:8983/solr/numishare/update`.

After this, then commit the changes by posting `<commit/>` to the same URL.

**Comment by Msch0150** [comment]
Works!
For documentation. Just in case I loose my notes or if someone else might want to use it (Linux).
Preparation:
Create a local file (example: /tmp/getIds):
```
xquery version "3.1" encoding "UTF-8";
declare namespace rdf = "http://exist-db.org/xquery/request";
declare namespace tei = "http://www.tei-c.org/ns/1.0";
<report> {
    for $i at $position in
        collection()[descendant::*[local-name() = 'publicationStatus'] = 'approved' or 
		descendant::*[local-name() = 'publicationStatus'] = 'approvedSubtype' or 
		descendant::tei:revisionDesc/@status = 'approved']
    return
        concat(if ($i//*:recordId) then
                   data($i//*:recordId)
               else
                   data($i/descendant::tei:idno[@type = 'filename'])
               ,
               if ($position mod 100 = 0) then
                   ','
               else
                   '|'
               )
}
</report>
```
Upload the file to the collection:
```
curl -u admin:my_password --upload-file \
  /tmp/getIds.xql http://localhost:my_exist_port/exist/rest/db/my_collection/
```

To publish the items:
```
for i in \
    $(curl -s http://admin:my_password@localhost:my_exist_port/exist/rest/db/my_collection/getIds.xql | \
      sed -n 's:.*<report>\(.*\)</report>.*:\1:p' | \
      sed s/\ //g | sed s/\,/\ /g); \
  do (curl --get --data-urlencode "identifiers=${i}" \
      http://admin:my_password@localhost:my_numishare_port/orbeon/numishare/my_collection/ingest | \
      curl -H "Content-Type: application/xml" -X POST -d @- http://localhost:8983/solr/numishare/update && \
      echo '<commit/>' | \
      curl -H "Content-Type: application/xml" -X POST -d @- http://localhost:8983/solr/numishare/update); \
done
```

To unpublish the items:

```
echo '<delete><query>collection-name:my_collection</query></delete>' | \
  curl -H "Content-Type: application/xml" -X POST -d @- http://localhost:8983/solr/numishare/update && \
  echo '<commit/>' | \
  curl -H "Content-Type: application/xml" -X POST -d @- http://localhost:8983/solr/numishare/update
```
