### ISSUE TITLE
CRRO Map tab

### ISSUE THREAD

**Issue by Greekcoins** [ewg118/numishare#30]
There is no search facet for 'Type number'.  We really need this.

**Comment by ewg118** [comment]
This is a bit of a problem, because it doesn't make sense to make the coin type a facet in a coin type collection. There is only 1 instance of each term. I understand that it would be useful to select multiple checkboxes to see the geographic distribution of multiple coin types simultaneously, but the facet list for CRRO will contain 2000 entries. For OCRE, it will contain more than 22,000. It's not technically practical to implement this feature.

**Comment by Greekcoins** [comment]
Yes it makes perfect sense.  How else will I navigate directly to a type?  This will be one of the most common, if not the most common way in for users. Everyone knows that the Antony legionary denarii are rrc 544, so that is how they will come looking for them.  

In fact we have precisely this facet in the map search in chrr. We really need it as a search facet throughout both projects.

A

**Comment by ewg118** [comment]
Use the browse interface instead of the map interface? We have the coin type facet in CHRR because it is possible for a hoard to have multiple coin types. I did fix some code so that the link to display the map will appear on the browse page, even when none of the results have mints (but do have findspots). See http://numismatics.org/crro/results?q=fulltext%3ARRC+544*

The map interface isn't really capable of constructing the same complexity of queries as the browse interface, and I hesitate to enable a function that may ultimately choke the browser.
