### ISSUE TITLE
No findspot found

### ISSUE THREAD

**Issue by Msch0150** [ewg118/numishare#45]
Setup described in https://github.com/ewg118/numishare/issues/43

Create/Edit Coin > +Findspot Description > FindSpot

"Search" field:

Abdon
A*
*

I do see the progress bar completing in the top, but no results are found.

**Comment by Msch0150** [comment]
Info: Numishare admin > modify settings > Titles and URLs > Geonames API Key > "myusername"
(the username is an example, in fact I user a different username)

I also tried as well : username=myusername

"http://www.geonames.org/export/web-services.html" mentions always "username" but never "API key"

A manual search works: 
Example:
http://api.geonames.org/search?q=berlin&username=myusername

**Comment by Msch0150** [comment]
Info: I debugged the http traffic. So far I could not see any attempt to access api.geonames.org when I search for a findspot.

**Comment by ewg118** [comment]
The Findspot control had not been edited since 2012, and had been broken by subsequent software upgrades over the years. Geonames lookups are once again possible after entering the API key/username into the Numishare configuration file, and coordinates can also be manually entered. The indexing of Geonames coordinates or manually entered coordinates is now supported in Solr, and the findspots in both cases will appear in both the RDF output and the GeoJSON for the given object.
