### ISSUE TITLE
Date on Object cannot be removed

### ISSUE THREAD

**Issue by Msch0150** [ewg118/numishare#53]
Create a coin.
Typological Description > +Date on Object

Once expanded, it cannot be removed anymore. Even after entering a value > save it cannot be removed like other item (ex. Date range, ... (by a click on "x")).

**Comment by ewg118** [comment]
I have completely rewritten the dateOnObject so that it comforms to the XSD schema (requiring a date or date range) with an optional era. The machine readable dates conforming to the xs:date, xs:gYear, xs:gYearMonth are optional (if they can be converted). The human readable label may be something like "COS IIII" or a brief textual description of a symbol or monogram. The human readable label is required, but there are no particular restrictions on content.
