### ISSUE TITLE
Add state via UI

### ISSUE THREAD

**Issue by Msch0150** [ewg118/numishare#67]
Create a new coin,
Authority +
state +
The menu closes but nothing additional appears on the page.

**Comment by ewg118** [comment]
I have rewritten the entity lookup mechanisms that occur within "authority", "obverse", and "reverse" so that the role between a an entity (whether a person, corporate entity, or dynasty) is selected by a drop down menu. I have eliminated individual links to insert Corporate Authority and Personal Authority. The correct XML element will be inserted based on the RDF class of the concept in Nomisma. I have eliminated "state" as a role, since this is effectively the "authority". State has no direct correlation in the Nomisma ontology.
