### ISSUE TITLE
Date text not available for different languages

### ISSUE THREAD

**Issue by Msch0150** [ewg118/numishare#71]
Admin UI > create Coin > Date > "0010" > Date (human-readable) gets filled to "10 AD".
It is possible to change this value to "10 n. Chr." (de) but this entered value is displayed for all languages.

Info: If I add manually in the xml file something like (example with fromDate (similar)):

    <fromDate standardDate="0010" xml:lang="de">10 n. Chr.</fromDate>
    <fromDate standardDate="0010" xml:lang="en">10 AD</fromDate>

Then I do get both entries displayed.

**Comment by ewg118** [comment]
I'll test whether XSLT's format-date function will work with locales.

**Comment by ewg118** [comment]
The format-date() function in XSLT 2.0 does allow for different languages and calendars ([https://www.w3.org/TR/xslt20/#format-date](https://www.w3.org/TR/xslt20/#format-date)), but it isn't actually fully implemented in the open source Saxon library. The multilingual labels for months work in Saxon 9.1 (which comes packaged in Orbeon), but the calendar/era don't seem to be supported outside of the standard "AD"/"BC". The open source version of Saxon 9.9 offers even less--the months aren't translated at all. It may be possible to create a limited, customized format-date() function (in the numishare: namespace) that can translate months and eras from a limited subset of commonly-used languages (English, French, and German, probably).

**Comment by ewg118** [comment]
I've more recently standardized the `numishare:normalizeDate` function to use BCE rather than BC. This function is used in many different serializations to convert the ISO date into a human-readable date, in HTML, GeoJSON, JSON for d3js, KML, etc., and not all of these contexts are easily able to make use of a lang parameter to distinguish between locales for AD/BC variations. I think it's simpler to apply CE and BCE across all languages because they are commonly understood. I replaced AD and BC with CE and BCE in the various drop down menus throughout Numishare.
