### ISSUE TITLE
mark in nuds

### ISSUE THREAD

**Issue by Msch0150** [ewg118/numishare#77]
If you add a countermark via the UI then the xml looks similar to:

    <countermark>
      <obverse>
        <mark>
          <description>IMP</description>
        </mark>
      </obverse>
    </countermark>

But "mark" is not listed in nuds [http://nomisma.org/nuds#obverse](http://nomisma.org/nuds#obverse). 
Currently it is not a real problem. 
But is it missing in the NUDS documentation or just a bug/feature in numishare?

I need to add countermarks where it is not known if they are placed on obverse or reverse. Can this officially be handled with nuds? My tests show that it works when I just do it like:

    <countermark>
      <description>IMP</description>
    </countermark>

But, as far as I can see, this is not defined and might lead into issues in the future, am I right?

**Comment by ewg118** [comment]
I believe this is an oversight where the development of the "obverse" element in several areas of the XSD schema began to differ from the XML model that was created in the XForms engine. The NUDS model wasn't formalized as an XSD schema until years after the development of various stages of the editing interface. Instead of a `mark` element, I think it makes more sense to allow any combination of `nuds:symbol`, `nuds:legend`, and the generic `nuds:description` for any free text within the obverse or reverse countermark. The "mark" is still a symbol, semantically, and the symbol element will enable more sophisticated linking to monogram/symbol URIs, position, etc. I will update the schema and the editing interface to allow the generic description element for countermark as well.

It's important to note that the XForms engine (with XPath-based validation) enables greater granularity than the XSD standard. So the XSD schema says that you can enter other "obverse" elements under countermark/obverse (like entities, type description, type series), but these probably shouldn't be used in most cases.

**Comment by ewg118** [comment]
I believe I have implemented a solution for this. The mark element has been deprecated from the XForms backend since it isn't in the schema. The testmark and countermark have the same model. You can choose between a general description or 0 or more symbols to insert directly in the testmark/countermark. This is when the coin is too worn to be able to clearly identify the obverse and the reverse. If you want to assign the mark at the obverse or reverse level, you can select "Obverse Features" or "Reverse Features". The XSD would allow you to choose any of the elements from the sideCharacteristics group (legend, symbol, etc.), but I recommend the following (which are enabled in the editing interface): legend, general, free-text description (not type description), entity (you can choose from issuer, authority, or mint. I think these are the types of entities that a countermark would refer to.), and 0 or more symbols. There could be multiple symbols for multiple countermarks. Symbols are only free-text now, but ideally symbols should have their own URI with further Linked Data metadata.
