### ISSUE TITLE
References

### ISSUE THREAD

**Issue by Msch0150** [ewg118/numishare#79]
Assume 'recordType="conceptual"' and create a coin which references to ocre:

        <refDesc>
            <reference xlink:type="simple" xlink:href="http://numismatics.org/ocre/id/ric.1(2).aug.154" />
            <reference xlink:type="simple" xlink:href="http://numismatics.org/ocre/id/ric.1(2).aug.155" />
            <reference xlink:type="simple" xlink:href="http://numismatics.org/ocre/id/ric.1(2).aug.156" />
            <reference xlink:type="simple" xlink:href="http://numismatics.org/ocre/id/ric.1(2).aug.157" />
        </refDesc>

Numishare does not load the info like "titel" from OCRE. So, only an icon to the reference is displayed.
It would be nice  if it would act like for other xlinks as well (example:
`<objectType` xlink:href="http://nomisma.org/id/coin" xlink:type="simple"/>
to display language sensitive "pref label" (here title).

Is this function available? Maybe by using a different link?

Additional info 1:
Maybe similar to: https://github.com/ewg118/numishare/issues/73

Additional info 2:
I assume that 
http://numismatics.org/pella/id/price.1
shows the same behavior for the reference (icon only).

**Comment by ewg118** [comment]
Is this a physical coin with 4 possible attributions to RIC? The title loads for Nomisma URIs since Numishare is programmed to read labels from a Nomisma API and display labels based on a `lang` URL parameter or HTTP language request headers. It isn't programmed to read the title from OCRE given the current structure of embedding the URI in a reference element. The underlying OCRE data will be loaded if you place an `xlink:arcrole` attribute on those reference elements with a value of `nmo:hasTypeSeriesItem`. I could update the Numishare code to display the title--but you'll have to update your underlying data to include the xlink:arcrole element. See [http://coins.lib.virginia.edu/id/1991.17.10.xml](http://coins.lib.virginia.edu/id/1991.17.10.xml)

**Comment by ewg118** [comment]
I have completely overhauled the reference lookup in the Numishare backend and made some significant modification to the HTML output and Solr indexing for references. First, in your example, a recordType='conceptual' should only be applied for a coin type. Data for physical coins should have a recordType='physical'. 

**Required:** In order to load the underlying NUDS record from OCRE, the xlink:arcrole attribute on the reference needs to have the string 'nmo:hasTypeSeriesItem'. 

If the "title" is left blank, then Numishare will attempt to load either the English title or the first title listed (if no English) from OCRE or other type corpus.

In the editing interface, there is now a 'link' button next to the title input to insert a new input for the coin type URI.

![screenshot from 2019-02-12 15-25-46](https://user-images.githubusercontent.com/563187/52665837-9fc8dc80-2eda-11e9-999d-8b8fb44915b5.png)

When you click "Search", the URI will be validated and either 1) display an error message when the URI is invalid or 2) do one of the two following:

- If it is an type corpus on an older version of the NUDS schema (OCRE, CRRO, PELLA, SCO), the title will be extracted from the NUDS record for the coin type and embedded in the nuds:reference element. The xlink:href will be set to the coin type URI and the xlink:arcrole will be set to 'nmo:hasTypeSeriesItem', making it possible to index these metadata into Solr and to display 1 or more mints in the GeoJSON map, when applicable.
- If the corpus is PCO (and the other Hellenistic Royal Coinages types will be updated soon) and contains a `otherRecordId[@localType='typeNumber']` in the control and a typeSeries element in the typeDesc, then these will be parsed from the target type NUDS record and incorporated into the reference as a `tei:title` and `tei:idno`. The other attributes will be set accordingly. Additionally, an xlink:title attribute will be set on the nuds:reference to store the type's title (since this varies from the typeSeries title, which is from Nomisma). This @xlink:title is used in the HTML interface and indexed into Solr as the coin type or reference facet term.

The output generated by Numishare's back-end for a PCO URI is as follows:

    <reference xlink:href="http://numismatics.org/pco/id/cpe.1_1.158" xlink:arcrole="nmo:hasTypeSeriesItem" xlink:type="simple" xlink:title="Coins of the Ptolemaic Empire Vol. I, Part 1, no. 158">
        <tei:title key="http://nomisma.org/id/coins_ptolemaic_empire">Coins of the Ptolemaic Empire</tei:title>
        <tei:idno>158</tei:idno>
    </reference>

**One other note:** If you are linking a coin to more than one type in the same corpus (1 or more OCRE URIs), it's highly recommended to insert an uncertainty modifier, with the attribute `certainty='http://nomisma.org/id/uncertain_value'`. The HTML interface will now display multilingual labels for Nomisma URIs in the @certainty attribute. At present, uncertain type attributes are suppressed from the RDF output in Numishare, but I will implement the proposed uncertainty model for type attribution eventually.
