### ISSUE TITLE
Issues with Digital Representations

### ISSUE THREAD

**Issue by clarerowan** [ewg118/numishare#83]
Manually edited NUDS xml doesn't show images in the coin or results fields when IIIF and thumbnail versions are provided.

**Comment by ewg118** [comment]
Has this been resolved?

**Comment by denseflux** [comment]
In some way, it could be more generalised. But not fixed yet, no. Scanning /ui/xslt/Ajax/results_ajax.xsl, I believe this is tied-up in the nomisma SPARQL overhaul you mentioned in #87. So I think it’s best we wait on that?

**Comment by denseflux** [comment]
To clarify from the issue title, it doesn’t matter whether the nuds is generated through the Numishare Orbeon Forms or manually edited.

**Comment by ewg118** [comment]
To clarify, are the images visible in the token-specimens site? But just not visible in token-types?

**Comment by denseflux** [comment]
Correct, yes. They are visible in token-specimens. But not in token-types.

Sent from my mobile

________________________________

**Comment by ewg118** [comment]
Okay. This will resolve itself once 1) the token-types collection Numishare config is updated to the URL of your locally deployed SPARQL endpoint and 2) I have updated the code for the browse page and results_ajax.xsl to use the local SPARQL endpoint instead of a Nomisma.org API. The type record page will currently display specimens in the local endpoint.

For example, I developed an unpublicized API in Nomisma called numishareResults (http://nomisma.org/apis/numishareResults?identifiers=ric.1(2).aug.1A&baseUri=http%3A%2F%2Fnumismatics.org%2Focre%2Fid%2F) that would streamline the display of these items by making Numishare issue a single HTTP call to Nomisma.org (which at the time was on a different server than ANS projects). Nomisma would then iterate through a series of internal SPARQL queries for each ID in the browse page/results_ajax and deliver an aggregated XML model back to Numishare, which is then processed into the HTML snippets for images and specimen/hoard count.

**Comment by ewg118** [comment]
I rewrote the pipeline for the browse and results_ajax serializations so that Numishare will chain together a series of SPARQL queries internally through its own implementation of the numishareResults API for a locally-defined SPARQL endpoint URL. If the SPARQL endpoint is still nomisma.org, it will use Nomisma's own API. These HTTP requests are defined in the XPL for `xpl/views/ajax/numishare_results.xpl` and `xpl/views/serializations/solr/html.xpl`

**Comment by ewg118** [comment]
![Screenshot from 2019-04-01 16-07-35](https://user-images.githubusercontent.com/563187/55356509-df528480-5498-11e9-8500-44263d9cc3f0.png)
The token-specimens don't have image URLs defined in the data I have, but they would display on my test interface.

**Comment by denseflux** [comment]
Excellent. Pulled the latest code, and confirm this is working locally for us here. Thanks.
