### ISSUE TITLE
nmo:hasCollection not present in the nomisma rdf from known sources

### ISSUE THREAD

**Issue by denseflux** [ewg118/numishare#87]
type-examples.sparql contains
```
?object nmo:hasCollection ?colUri .
?colUri skos:prefLabel ?collection 
```
Yet none of the rdf files that we import nomisma rdf (either void or nuds seem to contain any `nmo:hasCollection` triples. Where do these get generated, please? And are there circumstances where this would be different to the dcterms:title in void:Dataset?

**Comment by ewg118** [comment]
Typically, before we ingest a dataset from a museum collection into the Nomisma SPARQL endpoint, we'll create a Nomisma URI for the collection. There are circumstances where the dataset isn't from a collection with a definable Nomisma URI, which is why that part is optional in the type-examples SPARQL query. The dcterms:title in the VoID RDF will be displayed when the nmo:hasCollection isn't set. There are several instances where the dcterms:title is different than the collection. The Valencia Prehistory Museum publishes their data and the data from the Lliria archaeological museum in one dump. KENOM publishes several German museum collections in one dump as well. So the title of the dump is KENOM, but there are coins with the collection http://nomisma.org/id/mk_munich and others in the dump.

**Comment by ewg118** [comment]
I should also add that I'm doing some major overhauls within Numishare to make it possible to run all of the quantitative analysis queries, type examples, contributor pages, etc. from a local SPARQL endpoint set in the config rather than relying on hard-coding the Nomisma SPARQL endpoint in some sections.
