### ISSUE TITLE
Numishare installation questions

### ISSUE THREAD

**Issue by jtstratford** [ewg118/numishare#92]
I have Numishare mostly running on Ubuntu 16.04. I'm using Tomcat 8.5, eXist-db 4.7.1, Solr 4.10.4, and Orbeon 2018 CE. I have two questions at this point.

My first question: When I first installed Numishare, it crashed when logging in as username:admin. I found that I was able to use Numishare with a different username, i.e. substituting "admin" with "numishare."

At this point, I'm using username: admin, password:'' for Tomcat and eXist-db. I'm using username: numishare, password:'' for Numishare admin, and that seems to work. 

However, if I input username:admin by mistake at /orbeon/numishare/admin/, Numishare still crashes (HTTP Status 403). It doesn't seem to matter whether or not I have username:admin defined in tomcat-users.xml.  I don't need to use username:admin, I'm just trying to stop it from crashing if I do. Is there a change that I could make? Would changing username: admin for Tomcat or eXist-db help with this? Can you think of any unintended consequences to changing the Numishare admin username?

My second question: I want to manage the Numishare collections on a local network. The default URLs for Numishare "Add new collection" are 

http://localhost:8080/orbeon/numishare//
http://localhost:8080/solr/numishare-published/

Is there a place to change localhost to local network name (in this instance 'hadestown') 
so that I end up with 

http://hadestown:8080/orbeon/numishare//
http://hadestown:8080/solr/numishare-published/

Thank you so much for all your help with this.

**Comment by ewg118** [comment]
The first thing: the eXist-db usernames and passwords are internal only to eXist-db. They don't derive from the tomcat-users.xml file. It's not quite clear from the eXist-db that this is the case. *if* you were to block off all of `/exist` in Tomcat, then the tomcat-users.xml would take effect, but otherwise eXist-db's authentication for CRUD operations is entirely siloed.

Next, I'm still unsure why there would be an error trying to log into /orbeon/numishare/admin/. Usernames in the tomcat-users.xml don't matter--only the roles. So you could create a `jstratform` username with the role `numishare-admin`, and you should be able to get into the back-end superadmin panel. You'll want to make sure that superadmin users don't have the `numishare-admin` role along with other possible roles that you have connected to individual projects. The superadmin user has access to all possible projects.

The network name can be changed in the Settings page for the project. On the "Add new collection" interface, the initial `localhost` is hard-coded into a template of the config.xml file that gets stored in eXist-db upon creation of the new project collection. The config template is in `/numishare/xforms/admin.xhtml` wherever you deployed Numishare on the server. See the lines for the `<url>` and and `<solr_published>`: https://github.com/ewg118/numishare/blob/master/xforms/admin.xhtml#L55
